services:

  nginx:
    build:
      context: ./nginx
    ports :
      - "443:443"
  
  mariadb:
    build:
      context: ./mariadb
    volumes:
      - /home/abalasub/data:/var/lib/mysql
volumes:
      mariadb_data: 